In [1]:
# Dependencies
import pandas as pd 
import numpy as np

In [2]:
# load CSV
file_two = "Resources/2016-FCC-New-Coders-Survey-Data.csv"

In [3]:
# Read with pandas--low_memory required to suppress errors about mixed data types
df = pd.read_csv(file_two, encoding="ISO-8859-1", low_memory=False)

In [4]:
# Take only columns 0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111
new_df = df.iloc[:, [
    0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111]]
new_df.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,...,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,office and administrative support,Employed for wages,male,0.0,30.0,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,food and beverage,Employed for wages,male,NaN,30.0,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,finance,Employed for wages,male,NaN,20.0,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20.0,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,education,Employed for wages,female,NaN,25.0,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN

In [5]:
# Change reading 0 and 1 to No and Yes, respectively
new_df = new_df.replace({0: "No", 1: "Yes"})
new_df

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,...,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,office and administrative support,Employed for wages,male,No,30,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,food and beverage,Employed for wages,male,NaN,30,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,finance,Employed for wages,male,NaN,20,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,education,Employed for wages,female,NaN,25,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN
5,34.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,finance,Self-employed freelancer,male,NaN,5,40000.0,NaN,bachelor's degree,English
6,23.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Singapore,software development,Employed for wages,male,NaN,8,32000.0,NaN,bachelor's degree,Computer Science
7,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United Kingdom,office and administrative support,Employed for wages,male,No,NaN,40000.0,NaN,master's degree (non-professional),Education
8,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,software development,Employed for wages,male,NaN,5,80000.0,NaN,bachelor's degree,Business Administration
9,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,NaN,Employed for wages,male,NaN,20,80000.0,NaN,master's degree (non-professional),Business Administration
10,57.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",...,United States of America,NaN,Self-employed business owner,male,No,8,20000.0,NaN,bachelor's degree,Computer Science
11,23.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Bangladesh,NaN,Not working and not looking for work,male,NaN,5,NaN,NaN,"some college credit, no degree",NaN
12,47.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Canada,health care,Employed for wages,male,NaN,5,90000.0,NaN,bachelor's degree,Mechanical Engineering
13,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,software development,Employed for wages,male,NaN,5,NaN,NaN,bachelor's degree,Business Administration
14,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"between 100,000 and 1 million",...,Bosnia & Herzegovina,sales,Self-employed business owner,male,Yes,2,NaN,NaN,"some college credit, no degree",NaN
15,31.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Russia,software development,Employed for wages,female,NaN,10,NaN,NaN,"professional degree (MBA, MD, JD, etc.)",Math
16,27.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,software development,Employed for wages,female,NaN,4,80000.0,NaN,bachelor's degree,Economics
17,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",...,United States of America,education,Employed for wages,male,NaN,5,17000.0,NaN,bachelor's degree,Music
18,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Canada,software development,Self-employed freelancer,male,NaN,2,16000.0,NaN,bachelor's degree,Music
19,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",...,Croatia,NaN,Not working but looking for work,male,No,20,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
20,32.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,more than 1 million,...,United States of America,NaN,Employed for wages,female,Yes,5,200000.0,Full-Stack Web Developer,master's degree (non-professional),Geology
21,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Doing an unpaid internship,female,NaN,NaN,NaN,NaN,bachelor's degree,Computer Science
22,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,No,10,100000.0,NaN,bachelor's degree,Computer Science
23,44.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,office and administrative support,Employed for wages,female,No,30,41000.0,NaN,bachelor's degree,Political Science
24,21.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,India,NaN,Not working but looking for work,male,NaN,25,NaN,NaN,bachelor's degree,Computer Science
25,21.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Not working but looking for work,male,NaN,25,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
26,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",...,South Africa,NaN,Self-employed freelancer,male,No,Yes,12000.0,NaN,high school diploma or equivalent (GED),NaN
27,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,...,United States of America,software development,Employed for wages,male,Yes,10,60000.0,NaN,"trade, technical, or vocational training",NaN
28,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,software development,Employed for wages,male,NaN,10,75000.0,Full-Stack Web Developer,bachelor's degree,Political Science
29,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"less than 100,000",...,United Kingdom,software development,Employed for wages,male,Yes,5,35000.0,NaN,master's degree (non-professional),Physics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15590,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,India,software development and IT,Employed for wages,male,NaN,2,200000.0,NaN,bachelor's degree,Computer Science
15591,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Brazil,software development and IT,Employed for wages,male,No,2,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Computer Systems Networking and Telecommunicat...
15592,43.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,male,Yes,3,200000.0,NaN,high school diploma or equivalent (GED),NaN
15593,29.0,Yes,No,NaN,No,Camp Code Away,NaN,No,NaN,more than 1 million,...,India,software development and IT,Employed for wages,female,No,5,200000.0,NaN,bachelor's degree,Accounting
15594,36.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,...,United States of America,finance,Employed for wages,male,Yes,Yes,200000.0,NaN,bachelor's degree,Engineering
15595,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Ukraine,software development and IT,Self-employed freelancer,male,No,30,200000.0,NaN,some high school,NaN
15596,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,"less than 100,000",...,Brazil,software development and IT,Employed for wages,male,Yes,2,200000.0,NaN,high school diploma or equivalent (GED),NaN
15597,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Ukraine,legal,Self-employed freelancer,male,NaN,6,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Law
15598,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"less than 100,000",...,United States of America,food and beverage,Employed for wages,male,Yes,20,200000.0,Full-Stack Web Developer,associate's degree,Computer and Information Systems Security
15599,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,male,NaN,5,200000.0,NaN,"some college credit, no degree",NaN
15600,28.0,Yes,Yes,Yes,No,Epicodus,36000.0,Yes,NaN,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,female,NaN,8,200000.0,NaN,bachelor's degree,Marketing
15601,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,legal,Employed for wages,male,NaN,10,200000.0,NaN,bachelor's degree,Criminal Justice and Safety Studies
15602,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,India,software development and IT,Employed for wages,male,NaN,50,200000.0,Data Scientist / Data Engineer,bachelor's degree,Mathematics
15603,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,software development and IT,Employed for wages,male,NaN,4,200000.0,NaN,bachelor's degree,Computer Science
15604,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",...,Norway,construction and extraction,Employed for wages,male,NaN,5,200000.0,Front-End Web Developer,"some college credit, no degree",NaN
15605,31.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Portugal,software development and IT,Employed for wages,male,NaN,5,200000.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15606,43.0,No,NaN,NaN,NaN,NaN,NaN,NaN,3,more than 1 million,...,Canada,legal,Self-employed business owner,male,Yes,3,200000.0,NaN,bachelor's degree,Physics
15607,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Philippines,software development,Self-employed freelancer,male,No,8,200000.0,NaN,no high school (secondary school),NaN
15608,43.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,...,United States of America,health care,Employed for wages,male,Yes,6,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical Engineering
15609,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Mexico,software development and IT,Employed for wages,male,No,16,200000.0,NaN,bachelor's degree,Software Engineering
15610,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,education,Employed for wages,male,NaN,5,200000.0,Front-End Web Developer,master's degree (non-professional),Religious Studies
15611,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,more than 1 million,...,Canada,software development and IT,Self-employed business owner,male,Yes,40,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical and Electronics Engineering
15612,45.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Employed for wages,female,NaN,2,200000.0,NaN,"some college credit, no degree",NaN
15613,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,...,South Africa,software development and IT,Employed for wages,male,Yes,4,200000.0,NaN,"trade, technical, or vocational training",NaN
15614,47.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",...,United States of America,finance,Employed for wages,male,NaN,3,26000.0,NaN,"trade, technical, or vocational training",NaN
15615,39.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Kenya,software development and IT,Self-employed freelancer,male,No,40,10000.0,NaN,bachelor's degree,Chemistry
15616,27.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,India,software development and IT,Employed for wages,male,No,15,10000.0,Front-End Web Developer,bachelor's degree,Electrical Engineering
15617,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Nigeria,NaN,Self-employed freelancer,male,NaN,14,48000.0,NaN,bachelor's degree,Chemistry
15618,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,Spain,education,Self-employed freelancer,male,NaN,10,10000.0,NaN,master's degree (non-professional),Math
15619,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,...,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,No,2,18000.0,NaN,bachelor's degree,Graphic Design

In [6]:
# Extract rows for only those who attended a bootcamp
attended_bootcamp = new_df.loc[new_df["AttendedBootcamp"] == "Yes", :]
attended_bootcamp

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,...,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
93,32.0,Yes,Yes,No,No,Codify Academy,NaN,No,NaN,"between 100,000 and 1 million",...,United States of America,"arts, entertainment, sports, or media",Self-employed business owner,male,NaN,20,67000.0,NaN,bachelor's degree,Biology
97,26.0,Yes,Yes,Yes,No,DaVinci Coders,45000.0,No,NaN,more than 1 million,...,United States of America,software development,Employed for wages,male,No,10,40000.0,NaN,master's degree (non-professional),Music
130,41.0,Yes,Yes,Yes,Yes,Coder Foundry,75000.0,Yes,3,"less than 100,000",...,United States of America,software development,Employed for wages,male,Yes,30,75000.0,NaN,"some college credit, no degree",NaN
159,26.0,Yes,Yes,No,No,General Assembly,NaN,No,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Not working and not looking for work,female,NaN,30,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
188,24.0,Yes,No,NaN,Yes,NaN,NaN,No,NaN,"between 100,000 and 1 million",...,Canada,NaN,Not working but looking for work,female,NaN,60,NaN,NaN,"some college credit, no degree",NaN
206,36.0,Yes,Yes,No,No,Thinkful,NaN,No,2,more than 1 million,...,Japan,NaN,A stay-at-home parent or homemaker,female,Yes,20,NaN,Mobile Developer,bachelor's degree,Communications
209,25.0,Yes,Yes,No,Yes,Flatiron School,NaN,Yes,NaN,more than 1 million,...,Mexico,NaN,Not working but looking for work,male,NaN,40,NaN,Full-Stack Web Developer,"professional degree (MBA, MD, JD, etc.)",Computer Science
236,52.0,Yes,Yes,Yes,No,General Assembly,45000.0,No,NaN,"between 100,000 and 1 million",...,United States of America,software development,Self-employed freelancer,male,NaN,30,45000.0,NaN,"some college credit, no degree",NaN
272,38.0,Yes,Yes,Yes,Yes,DevMountain,50000.0,Yes,NaN,"between 100,000 and 1 million",...,United States of America,software development,Employed for wages,male,NaN,5,NaN,NaN,bachelor's degree,Structural Engineering
273,35.0,Yes,Yes,Yes,Yes,The Iron Yard,60000.0,Yes,NaN,"between 100,000 and 1 million",...,United States of America,software development,Employed for wages,male,NaN,10,54000.0,NaN,bachelor's degree,Public Administration
285,23.0,Yes,Yes,Yes,No,Codeup,40000.0,Yes,NaN,NaN,...,United States of America,software development,Employed for wages,male,NaN,40,NaN,NaN,bachelor's degree,Journalism
315,31.0,Yes,Yes,No,No,General Assembly,NaN,No,NaN,"between 100,000 and 1 million",...,United States of America,software development,Self-employed freelancer,genderqueer,NaN,20,35000.0,User Experience Designer,bachelor's degree,Communications
316,22.0,Yes,Yes,No,No,Code Fellows,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Not working but looking for work,male,NaN,30,NaN,Front-End Web Developer,associate's degree,General Studies
328,30.0,Yes,No,NaN,No,Bloc.io,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,sales,Employed for wages,female,NaN,20,35000.0,Front-End Web Developer,bachelor's degree,Advertising and Marketing
426,30.0,Yes,Yes,No,Yes,General Assembly,NaN,Yes,NaN,"less than 100,000",...,United States of America,education,Employed for wages,male,NaN,40,NaN,Full-Stack Web Developer,bachelor's degree,Liberal Arts
435,26.0,Yes,Yes,No,Yes,The Firehose Project,NaN,Yes,NaN,more than 1 million,...,United States of America,NaN,Not working but looking for work,male,NaN,50,NaN,Front-End Web Developer,associate's degree,Psychology
449,38.0,Yes,Yes,No,No,General Assembly,NaN,Yes,NaN,more than 1 million,...,United States of America,NaN,Not working but looking for work,female,NaN,20,NaN,NaN,bachelor's degree,Architecture
465,40.0,Yes,No,NaN,Yes,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,NaN,A stay-at-home parent or homemaker,female,NaN,8,NaN,Quality Assurance Engineer,master's degree (non-professional),English
470,45.0,Yes,No,NaN,No,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Not working and not looking for work,female,NaN,50,NaN,Mobile Developer,bachelor's degree,Liberal Arts
478,37.0,Yes,No,NaN,Yes,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,NaN,NaN,female,NaN,50,NaN,Full-Stack Web Developer,bachelor's degree,Sociology
481,27.0,Yes,Yes,No,No,Prime Digital Academy,NaN,Yes,NaN,"less than 100,000",...,United States of America,NaN,Not working but looking for work,female,NaN,2,NaN,Front-End Web Developer,"trade, technical, or vocational training",NaN
488,25.0,Yes,No,NaN,Yes,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Unable to work,male,NaN,9,NaN,Front-End Web Developer,bachelor's degree,Psychology
505,28.0,Yes,Yes,Yes,Yes,Free Code Camp is not a bootcamp - please scro...,50000.0,Yes,Yes,more than 1 million,...,United States of America,software development and IT,Employed for wages,male,Yes,15,38000.0,NaN,"some college credit, no degree",NaN
506,38.0,Yes,Yes,No,No,Prime Digital Academy,NaN,Yes,2,more than 1 million,...,United States of America,NaN,Not working but looking for work,female,Yes,25,NaN,Back-End Web Developer,bachelor's degree,Anthropology
510,33.0,Yes,No,NaN,No,Flatiron School,NaN,Yes,NaN,more than 1 million,...,Australia,NaN,Not working and not looking for work,male,NaN,60,NaN,Full-Stack Web Developer,"trade, technical, or vocational training",NaN
522,33.0,Yes,Yes,No,Yes,Galvanize,NaN,No,NaN,"less than 100,000",...,United States of America,NaN,Employed for wages,male,NaN,10,NaN,Full-Stack Web Developer,bachelor's degree,Psychology
525,31.0,Yes,No,NaN,No,Ada,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Not working and not looking for work,female,NaN,50,NaN,Full-Stack Web Developer,bachelor's degree,Psychology
526,30.0,Yes,No,NaN,No,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,NaN,Not working but looking for work,female,NaN,50,NaN,Back-End Web Developer,bachelor's degree,Nutrition
533,20.0,Yes,No,NaN,No,NaN,NaN,Yes,NaN,"between 100,000 and 1 million",...,India,software development and IT,Employed for wages,male,NaN,6,6000.0,NaN,bachelor's degree,Communications
543,27.0,Yes,Yes,Yes,No,Skillcrush,58000.0,Yes,NaN,"less than 100,000",...,United States of America,software development and IT,Employed for wages,female,NaN,5,43000.0,NaN,bachelor's degree,Business Administration
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14653,29.0,Yes,Yes,Yes,No,Epicodus,50000.0,Yes,NaN,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,female,NaN,5,15600.0,NaN,bachelor's degree,Political Science
14681,24.0,Yes,Yes,No,No,Dev Bootcamp,NaN,Yes,NaN,more than 1 million,...,Ukraine,software development and IT,Self-employed freelancer,male,No,4,60000.0,NaN,bachelor's degree,Computer Science
14695,22.0,Yes,No,NaN,No,AcadGild,NaN,Yes,NaN,more than 1 million,...,India,software development and IT,Employed for wages,male,No,90,24000.0,NaN,bachelor's degree,Computer Science
14701,23.0,Yes,No,NaN,Yes,Devschool,NaN,Yes,NaN,"between 100,000 and 1 million",...,Romania,finance,Employed for wages,male,NaN,8,60000.0,Mobile Developer,some high school,NaN
14751,29.0,Yes,Yes,Yes,No,Orange County Code School,90000.0,No,NaN,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,male,No,20,48000.0,NaN,bachelor's degree,Industrial Engineering
14766,25.0,Yes,Yes,No,No,DaVinci Coders,NaN,No,NaN,"less than 100,000",...,United States of America,software development and IT,Self-employed business owner,male,NaN,50,48000.0,Full-Stack Web Developer,"trade, technical, or vocational training",NaN
14797,37.0,Yes,No,NaN,No,NaN,NaN,Yes,3,more than 1 million,...,Malaysia,software development and IT,Self-employed freelancer,male,Yes,20,28800.0,NaN,bachelor's degree,Electrical Engineering
14846,15.0,Yes,No,NaN,No,Free Code Camp is not a bootcamp - please scro...,NaN,Yes,NaN,"between 100,000 and 1 million",...,United States of America,education,Employed for wages,female,NaN,10,8400.0,Back-End Web Developer,some high school,NaN
14987,NaN,Yes,No,NaN,No,LAMP Camp,NaN,Yes,NaN,"less than 100,000",...,United States of America,office and administrative support,Employed for wages,female,NaN,40,60000.0,NaN,associate's degree,Computer Networking
14992,24.0,Yes,No,NaN,No,Flatiron School,NaN,Yes,NaN,more than 1 million,...,Nigeria,software development and IT,Employed for wages,male,No,10,51432.0,NaN,associate's degree,Software Engineering
15062,29.0,Yes,No,NaN,Yes,New York Code + Design Academy,NaN,Yes,NaN,more than 1 million,...,United States of America,NaN,Employed for wages,genderqueer,NaN,20,36000.0,DevOps / SysAdmin,"trade, technical, or vocational training",NaN
15106,24.0,Yes,Yes,Yes,No,Prime Digital Academy,50000.0,Yes,NaN,NaN,...,United States of America,software development and IT,Employed for wages,female,NaN,10,48000.0,NaN,"some college credit, no degree",NaN
15128,24.0,Yes,Yes,No,Yes,IronHack,NaN,Yes,NaN,more than 1 million,...,United States of America,software development and IT,Employed for wages,female,No,30,18000.0,Full-Stack Web Developer,associate's degree,Computer Science
15165,26.0,Yes,No,NaN,No,Bloc.io,NaN,Yes,NaN,"less than 100,000",...,United States of America,"arts, entertainment, sports, or media",Self-employed freelancer,male,NaN,40,48000.0,Full-Stack Web Developer,master's degree (non-professional),Music Performance
15188,29.0,Yes,No,NaN,No,Free Code Camp is not a bootcamp - please scro...,NaN,Yes,NaN,more than 1 million,...,Philippines,software development and IT,Employed for wages,female,No,25,28560.0,NaN,bachelor's degree,Engineering
15239,28.0,Yes,Yes,Yes,No,Prime Digital Academy,65000.0,Yes,NaN,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,male,NaN,45,48000.0,NaN,bachelor's degree,Neuroscience
15348,24.0,Yes,No,NaN,No,CodeNinja,NaN,Yes,NaN,more than 1 million,...,Vietnam,software development and IT,Self-employed freelancer,male,NaN,30,12000.0,NaN,high school diploma or equivalent (GED),NaN
15395,31.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,NaN,"between 100,000 and 1 million",...,Puerto Rico,legal,Employed for wages,female,NaN,6,60000.0,NaN,"some college credit, no degree",NaN
15400,32.0,Yes,No,NaN,No,Fire Bootcamp,NaN,No,NaN,more than 1 million,...,Saudi Arabia,software development and IT,Self-employed freelancer,female,NaN,12,24000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Computer Systems Networking and Telecommunicat...
15406,23.0,Yes,Yes,Yes,No,App Academy,79000.0,Yes,NaN,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,male,NaN,No,12000.0,NaN,bachelor's degree,History
15412,24.0,Yes,Yes,No,Yes,New York Code + Design Academy,NaN,Yes,NaN,"less than 100,000",...,United States of America,software development and IT,Self-employed freelancer,male,NaN,10,36000.0,Full-Stack Web Developer,bachelor's degree,English
15420,25.0,Yes,Yes,Yes,No,We Can Code IT,10000.0,No,NaN,more than 1 million,...,India,software development and IT,Employed for wages,male,No,NaN,12000.0,NaN,bachelor's degree,Information Technology
15421,22.0,Yes,Yes,No,No,NaN,NaN,Yes,NaN,more than 1 million,...,Nigeria,software development and IT,Self-employed freelancer,male,NaN,30,7200.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15436,45.0,Yes,No,NaN,No,Starter League,NaN,Yes,Yes,"between 100,000 and 1 million",...,Ukraine,construction and extraction,Self-employed freelancer,male,Yes,5,36000.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15465,25.0,Yes,No,NaN,No,CodeaCamp,NaN,Yes,NaN,"between 100,000 and 1 million",...,Ukraine,architecture or physical engineering,Employed for wages,male,NaN,15,14400.0,Back-End Web Developer,master's degree (non-professional),Electrical and Electronics Engineering
15539,39.0,Yes,Yes,Yes,Yes,CodeaCamp,NaN,Yes,NaN,more than 1 million,...,Mexico,NaN,Self-employed freelancer,female,NaN,15,36000.0,Full-Stack Web Developer,"some college credit, no degree",NaN
15540,24.0,Yes,Yes,Yes,Yes,Anyone Can Learn To Code,NaN,No,NaN,more than 1 million,...,Kenya,"arts, entertainment, sports, or media",Employed for wages,female,NaN,10,16800.0,NaN,bachelor's degree,Computer Systems Networking and Telecommunicat...
15541,23.0,Yes,Yes,Yes,No,CodeaCamp,21600.0,Yes,NaN,more than 1 million,...,Mexico,software development and IT,Employed for wages,male,NaN,24,42000.0,NaN,master's degree (non-professional),Computer Software Engineering
15593,29.0,Yes,No,NaN,No,Camp Code Away,NaN,No,NaN,more than 1 million,...,India,software development and IT,Employed for wages,female,No,5,200000.0,NaN,bachelor's degree,Accounting
15600,28.0,Yes,Yes,Yes,No,Epicodus,36000.0,Yes,NaN,"between 100,000 and 1 million",...,United States of America,software development and IT,Employed for wages,female,NaN,8,200000.0,NaN,bachelor's degree,Marketing

In [53]:
# Create DataFrame of the different boot camps that had a significant number of attendees
bootcamp_name = pd.DataFrame(attended_bootcamp["BootcampName"].value_counts())
bootcamp_name.reset_index(inplace=True)
bootcamp_name.rename(columns={'index':'Boot Camp Name', 'BootcampName': 'Amt_Who_Attended'}, inplace=True)
bootcamp_name = bootcamp_name[bootcamp_name.Amt_Who_Attended.between(9, 100)]
bootcamp_name
# I restricted the significant number of attendees to any bootcamp that had 9 or more attendees here with the function above

                                       Boot Camp Name  Amt_Who_Attended
0                                    General Assembly                90
1                                     Flatiron School                54
2                                        Dev Bootcamp                48
3                                       The Iron Yard                40
4                               Prime Digital Academy                30
5                                        Hack Reactor                29
6                                              Turing                27
7                                         App Academy                22
8                                  Hackbright Academy                22
9                                             Bloc.io                21
10                                       Code Fellows                21
11                                          Galvanize                20
12                                        MakerSquare                20
13                     New York Code + Design Academy                20
14                                        Coding Dojo                18
15                               The Firehose Project                16
16  Free Code Camp is not a bootcamp - please scro...                15
17                                           Epicodus                14
18                                        Dev Academy                13
19                                     Makers Academy                12
20                                  Tech Talent South                12
21                                        Coder Camps                11
22                                     Launch Academy                10
23                                 Viking Code School                10
24                                     Software Guild                10
25                                        DevMountain                10
26                                             Codeup                10
27                                                Ada                 9

In [54]:
# Count how many attendees of each bootcamp would recommend the bootcamp
recommended_bootcamp = attended_bootcamp.replace({"Yes": 1, "No": 0})
recommended_bootcamp = pd.DataFrame(recommended_bootcamp.groupby("BootcampName")["BootcampRecommend"].sum())
recommended_bootcamp.reset_index(inplace=True)

recommended_bootcamp.rename(columns={'BootcampName':'Boot Camp Name', 'BootcampRecommend': 'Amt Who Recommended'}, inplace=True)
recommended_bootcamp.head()

          Boot Camp Name  Amt Who Recommended
0             10x.org.il                  3.0
1         4Geeks Academy                  4.0
2               AcadGild                  2.0
3    Academia de CÃƒÂ³digo                  4.0
4  Academic Work Academy                  0.0

In [56]:
# Merge the two created data frames on the name of the bootcamp
merge_table = pd.merge(bootcamp_name, recommended_bootcamp, on="Boot Camp Name")
merge_table

,Boot Camp Name,Amt_Who_Attended,Amt Who Recommended
0,General Assembly,90,70.0
1,Flatiron School,54,50.0
2,Dev Bootcamp,48,41.0
3,The Iron Yard,40,31.0
4,Prime Digital Academy,30,25.0
5,Hack Reactor,29,27.0
6,Turing,27,26.0
7,App Academy,22,20.0
8,Hackbright Academy,22,19.0
9,Bloc.io,21,11.0
10,Code Fellows,21,15.0
11,Galvanize,20,11.0
12,MakerSquare,20,18.0
13,New York Code + Design Academy,20,14.0
14,Coding Dojo,18,11.0
15,The Firehose Project,16,13.0
16,Free Code Camp is not a bootcamp - please scro...,15,14.0
17,Epicodus,14,11.0
18,Dev Academy,13,13.0
19,Makers Academy,12,12.0
20,Tech Talent South,12,8.0
21,Coder Camps,11,6.0
22,Launch Academy,10,8.0
23,Viking Code School,10,10.0
24,Software Guild,10,8.0
25,DevMountain,10,8.0
26,Codeup,10,6.0
27,Ada,9,8.0

In [59]:
# Calculate percentage of each bootcamp's students who are recommenders
merge_table['Percent Recommended'] = 100*merge_table['Amt Who Recommended']/merge_table['Amt_Who_Attended']

merge_table = merge_table.round(2)
merge_table = merge_table.sort_values(by='Percent Recommended', ascending=False)
merge_table

,Boot Camp Name,Amt_Who_Attended,Amt Who Recommended,Percent Recommended
18,Dev Academy,13,13.0,100.00
23,Viking Code School,10,10.0,100.00
19,Makers Academy,12,12.0,100.00
6,Turing,27,26.0,96.30
16,Free Code Camp is not a bootcamp - please scro...,15,14.0,93.33
5,Hack Reactor,29,27.0,93.10
1,Flatiron School,54,50.0,92.59
7,App Academy,22,20.0,90.91
12,MakerSquare,20,18.0,90.00
27,Ada,9,8.0,88.89
8,Hackbright Academy,22,19.0,86.36
2,Dev Bootcamp,48,41.0,85.42
4,Prime Digital Academy,30,25.0,83.33
15,The Firehose Project,16,13.0,81.25
24,Software Guild,10,8.0,80.00
22,Launch Academy,10,8.0,80.00
25,DevMountain,10,8.0,80.00
17,Epicodus,14,11.0,78.57
0,General Assembly,90,70.0,77.78
3,The Iron Yard,40,31.0,77.50
10,Code Fellows,21,15.0,71.43
13,New York Code + Design Academy,20,14.0,70.00
20,Tech Talent South,12,8.0,66.67
14,Coding Dojo,18,11.0,61.11
26,Codeup,10,6.0,60.00
11,Galvanize,20,11.0,55.00
21,Coder Camps,11,6.0,54.55
9,Bloc.io,21,11.0,52.38

In [ ]:
# Export to excel and remove index